version: '3.8'
services:
  db:
    container_name: postgres_for_candle_lab
    image: postgres:14.1
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

networks:
  default:
    driver: bridge

volumes:
    db:
      driver: local